[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200